---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: __IMAGE__
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: ENV
              value: __ENV__
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
